version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:focal
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      TZ: "Europe/Zurich"
    steps:
      - checkout
      - run:
          name: "Install Packages"
          command: apt-get update && apt-get install -y gcc g++ git cmake libssl-dev python3-pip libxml2-utils
      - run:
          name: "Setup Git"
          command: git config --global user.email "woodtli@.circleciexample.com" && git config --global user.name "Woodtli circleci"
      - run:
          name: "Install conan"
          command: pip3 install conan
      - run:
          name: "create builddir"
          command: mkdir build
      - run:
          name: "Set c++11 ABI"
          command: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - run:
          name: "Install dependencies"
          working_directory: build
          command: conan install ..
      - run:
          name: "Run cmake"
          working_directory: build
          command: source activate_run.sh && cmake ..
      - run:
          name: "make"
          working_directory: build
          command: source activate_run.sh && make
workflows:
  build-workflow:
    jobs:
      - build
